### ISSUE TITLE
Unable to create new campaign

### ISSUE THREAD

**Issue by raffomartini** [GoogleCloudPlatform/emblem#379]
## Problem

I have the website and the api server running.
oAuth is configured and working.
When I create a new campaign, POST/ createCampaign fails with Error 500.

## Steps to Reproduce

1. website and the api server running.
2. Click on 'Create new campaign'
3. Fill in the form
4. Error 500: Internal Server Error

## Expected behavior

A new campaign should be created
## Additional context

**Screenshots**
![Error](https://user-images.githubusercontent.com/24324516/168854560-42667de3-7bd3-49df-9e34-56d270d9f165.jpg)

**User environment:**
 - Chrome for MACOS
 - cloudshell
 -both API and webserver running on cloud run

**Comment by raffomartini** [comment]
Traceback points to [`website/views/campaigns.py` ](https://github.com/GoogleCloudPlatform/emblem/blob/main/website/views/campaigns.py)
```
Traceback (most recent call last):
  File "/app/views/campaigns.py", line 59, in save_campaign
    "cause": request.form["cause"],
  File "/usr/local/lib/python3.9/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

I suspect the actual issue is the template [`website/templates/create-campaign.html`](https://github.com/GoogleCloudPlatform/emblem/blob/main/website/templates/create-campaign.html)
I believe there is no ID specified for the cause in line 66 through 92, but I know very little of web dev and can be wrong 😇 
```
        <!-- Causes list -->
        <label class="emblem-new-campaign-input mdc-select mdc-select--filled">
          <div class="mdc-select__anchor">
            <span class="mdc-select__ripple"></span>
            <span class="mdc-select__selected-text"></span>
            <span class="mdc-select__dropdown-icon">
              <svg class="mdc-select__dropdown-icon-graphic" viewBox="7 10 10 5">
                <polygon class="mdc-select__dropdown-icon-inactive" stroke="none" fill-rule="evenodd" points="7 10 12 15 17 10">
                </polygon>
                <polygon class="mdc-select__dropdown-icon-active" stroke="none" fill-rule="evenodd" points="7 15 12 10 17 15">
                </polygon>
              </svg>
            </span>
            <span class="mdc-floating-label">Cause for Campaign</span>
            <span class="mdc-line-ripple"></span>
          </div>
          <div class="mdc-select__menu mdc-menu mdc-menu-surface mdc-menu-surface--fullwidth">
            <ul class="mdc-list">
              {% for cause in causes %}
                <li class="mdc-list-item" data-value="{{ cause.id }}">
                  <span class="mdc-list-item__ripple"></span>
                  <span class="mdc-list-item__text">{{ cause.name }}</span>
                </li>
              {% endfor %}
            </ul>
          </div>
        </label>
```

**Comment by raffomartini** [comment]
After fixing #403  Charlie and I could verify the issue is with the new-campaign template.
Specifically, the cause selected in the dropdown is not sent to the server.
Check raffo-379 branch for debug code.

Charlie suggested to assign the issue to Ace.
