### ISSUE TITLE
API Service 500 errors when following setup-quickstart.md & new terraform configuration

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#486]
## Problem

When following [setup-quickstart](https://github.com/GoogleCloudPlatform/emblem/docs/tutorials/setup-quickstart.md) and using the new terraform configuration, the resulting API service throw 500 errors.

The error logs & responses are unclear, and some of the logs produced are parsed as multiple log entries which makes scanning difficult.

## Analysis

It looks like the Content API as deployed lacks IAM read access to Firestore, and this is handled with convoluted log output that makes verifying the problem difficult. If so, a change to fix this would be to adjust the IAM privileges on the Content API service identity.

Follow-up tasks to improve log-based troubleshooting would help. Because this is a demo, it would be worth evaluating if exposing the error more clearly in the HTTP response would be helpful and not lead folks to a production anti-pattern.

## Steps to Reproduce

Log entries from my installation:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/main.py", line 85, in handle_list
    return methods.list(resource_name)
  File "/app/resources/methods.py", line 50, in list
    if not auth.allowed("GET", resource_kind):
  File "/app/resources/auth.py", line 55, in allowed
    is_approver = user_is_approver(email)
  File "/app/resources/auth.py", line 26, in user_is_approver
    matching_approvers = db.list_matching(
  File "/app/data/cloud_firestore.py", line 47, in list_matching
    for resource_ref in query.stream():
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/query.py", line 273, in stream
    response_iterator, expected_prefix = self._get_stream_iterator(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/query.py", line 218, in _get_stream_iterator
    response_iterator = self._client._firestore_api.run_query(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1236, in run_query
    response = rpc(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 151, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 Missing or insufficient permissions.
```
and
```
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'content-type': 'text/html; charset=utf-8', 'X-Cloud-Trace-Context': 'b43e6df168c33c04bdb1eee2b06bb27b;o=1', 'Date': 'Mon, 06 Jun 2022 15:58:21 GMT', 'Server': 'Google Frontend', 'Content-Length': '265', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'})
HTTP response body: <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by grayside** [comment]
This issue seems to be closely related to #254, or at the very least fixing it without being part of or following-up that issue will create conflict & rework.
