### ISSUE TITLE
exclude `website/e2e-test` from web-e2e-test build trigger glob

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#741]
## Problem
Currently the `web-e2e-test` build trigger is invoked by pull requests that include changes to `website/**`.  This leads to failures when dependencies are updated for the e2e-test container build ([example](https://github.com/GoogleCloudPlatform/emblem/pull/721/checks?check_run_id=10102767595))

## Steps to Reproduce

1. Create a pull request with a change to the website/e2e-test/package.json
2. web-e2e-test will fail 

## Expected behavior

`web-e2e-test` should only run on changes to website container build and not its testing.  

## Additional context
Example test output: 
```sh
Running 8 tests using 1 worker

  ✘  1 smoke-test.spec.js:35:1 › Renders homepage (11ms)
  ✘  2 smoke-test.spec.js:39:1 › Renders login (10ms)
  ✘  3 smoke-test.spec.js:43:1 › Renders logout (10ms)
  ✘  4 smoke-test.spec.js:47:1 › Renders donate (10ms)
  ✘  5 smoke-test.spec.js:51:1 › Renders viewCampaign (10ms)
  ✘  6 smoke-test.spec.js:55:1 › Renders createCampaign (10ms)
  ✘  7 smoke-test.spec.js:59:1 › Renders viewDonation (10ms)
  ✘  8 system-test.spec.js:24:1 › Lists Campaigns (10ms)


  1) smoke-test.spec.js:35:1 › Renders homepage ====================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  2) smoke-test.spec.js:39:1 › Renders login =======================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  3) smoke-test.spec.js:43:1 › Renders logout ======================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  4) smoke-test.spec.js:47:1 › Renders donate ======================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  5) smoke-test.spec.js:51:1 › Renders viewCampaign ================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  6) smoke-test.spec.js:55:1 › Renders createCampaign ==============================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  7) smoke-test.spec.js:59:1 › Renders viewDonation ================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81

  8) system-test.spec.js:24:1 › Lists Campaigns ====================================================

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1033/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.28.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.27.1-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.28.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

        at Object._baseTest.extend.browser.scope [as fn] (/workspace/website/e2e-test/node_modules/@playwright/test/lib/index.js:188:51)
        at /workspace/website/e2e-test/node_modules/@playwright/test/lib/fixtures.js:95:81


  8 failed
    smoke-test.spec.js:35:1 › Renders homepage =====================================================
    smoke-test.spec.js:39:1 › Renders login ========================================================
    smoke-test.spec.js:43:1 › Renders logout =======================================================
    smoke-test.spec.js:47:1 › Renders donate =======================================================
    smoke-test.spec.js:51:1 › Renders viewCampaign =================================================
    smoke-test.spec.js:55:1 › Renders createCampaign ===============================================
    smoke-test.spec.js:59:1 › Renders viewDonation =================================================
```

**Comment by rogerthatdev** [comment]
Solution A: update build trigger glob to exclude `website/e2e-test`.
Solution B: move `website/e2e-test` to separate directory in root (example: `/testing/web-e2e-test`)

Based on code pairing with @ace-n
